# **✅ Task 15: End-to-End Machine Learning Pipeline**

## **Importing Required Modules:**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,classification_report
import joblib

## **Load the dataset and separate features and target variable::**

In [4]:
data=load_breast_cancer(as_frame=True)

In [5]:
df=data.frame
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [6]:
X=df.drop("target",axis=1)
y=df["target"]

In [7]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [9]:
X.shape,y.shape

((569, 30), (569,))

## **Identify numerical and categorical features for preprocessing:**

In [15]:
numerical_features = X.select_dtypes(include=['float64']).columns
categorical_features = X.select_dtypes(include=['int64']).columns

In [16]:
numerical_features

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [20]:
categorical_features

Index([], dtype='object')

In [18]:
len(numerical_features),len(catogirical_features)

(30, 0)

## **Apply scaling and encoding using ColumnTransformer:**

In [19]:
from sklearn.compose import ColumnTransformer

In [23]:
transformer = ColumnTransformer(
    transformers=[
        ("cat",OneHotEncoder(),categorical_features),
        ("num",StandardScaler(),numerical_features)
    ]
)

## **Create a complete ML pipeline combining preprocessing and model:**

In [24]:
pipeline=Pipeline(steps=[
        ("preprocessor",transformer),
        ("model",LogisticRegression(max_iter=1000))
    ]
)

## **Split data into train and test sets:**

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## **Train the pipeline and generate predictions on test data:**

In [27]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index([], dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter erro...
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object'))])),
                ('model', LogisticRegression(max_iter=1000))])

In [28]:
y_pred = pipeline.predict(X_test)

In [34]:
accuracy_score(y_test,y_pred) * 100

97.36842105263158

In [35]:
precision_score(y_test,y_pred) * 100

97.22222222222221

In [36]:
recall_score(y_test,y_pred) * 100

98.59154929577466

In [37]:
f1_score(y_test,y_pred) * 100

97.9020979020979

## **Evaluate using accuracy, precision, recall, and F1-score:**

In [38]:
metric_data = pd.DataFrame(
    {
        "Model": ["Logistic Regression"],
        "Accuracy": [accuracy_score(y_test, y_pred)],
        "Precision":[precision_score(y_test, y_pred)],
        "Recall Score":[recall_score(y_test, y_pred)],
        "F1 Score":[f1_score(y_test, y_pred)]
    }
)

In [39]:
metric_data

                 Model  Accuracy  Precision  Recall Score  F1 Score
0  Logistic Regression  0.973684   0.972222      0.985915  0.979021

In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

## **Save the model:**

In [45]:
joblib.dump(pipeline,"breast_cancer_pipeline.pkl")

['breast_cancer_pipeline.pkl']